### ISSUE TITLE
dbsync and the sync_data.gpkg

### ISSUE THREAD

**Issue by northrivergeo** [MerginMaps/db-sync#136]
I preface everything I write as I'm two hours into what I think is the correct usage of dbsync. 

I have a postgresql/postgis database (14.11/3.4) . 
Current version of dbsync as of 20240305. 

If I follow the directions and download the project (nrgsinc/mobile) to symbolize the sync_data.gpkg that is where the fun starts. The Layers open as blank in QGIS (3.34.3) There is data there. I'm working in EPSG:2274. 

If I change the projection of the canvas to epsg:4326 and click "Zoom to layer" (by right clicking on the layer) the data appears. I then update the extent and create a spatial index and all is good. This may have something to do with the random warnings of downloading the us_noaa_tn.tif file. I didn't get that warning (I assume because dbsync shoves the data into the database) and my guess is Mergin Maps believes this is in 4326. 

It's a simple fix now that I know - but I worry someone else may not see that as simple. If you want to see an unaltered project you can go to nrgsinc/mobile_lutra and download the sync_data.gpkg and take a look.

**Comment by JanCaha** [comment]
This does not seem like dbsync issue, more likely issue with data and/or QGIS project.
