### ISSUE TITLE
I can't connect to database

### ISSUE THREAD

**Issue by 01mk027** [MerginMaps/db-sync#141]
Connecting to the database...
Unable to connect to the database: could not connect to server: Connection refused
	Is the server running on host "localhost" (::1) and accepting
	TCP/IP connections on port 5432?
could not connect to server: Connection refused
	Is the server running on host "localhost" (127.0.0.1) and accepting
	TCP/IP connections on port 5432?
I make all configurations but i am still getting this error?

**Comment by JanCaha** [comment]
This could be caused by some system settings, firewall or something like that. This does not seem like dbsync issue.
